# Generated by Django 3.1 on 2020-09-03 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=users.models.generate_integers, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField(default=users.models.generate_expire_date)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('language', models.CharField(default='en', max_length=20)),
                ('phone_number', models.TextField(null=True, unique=True)),
                ('birthday', models.DateField(null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=40, null=True)),
                ('google_id', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('has_channel', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('createda_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('url', models.URLField()),
                ('seen', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('to_channel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
