# Generated by Django 3.1 on 2020-09-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_use_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='createda_at',
            new_name='created_at',
        ),
    ]
