# Generated by Django 3.1 on 2020-09-30 11:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_history_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
