# Generated by Django 3.1 on 2020-10-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
