# Generated by Django 3.1 on 2020-10-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_saved_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_detected_country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
