# Generated by Django 3.1 on 2020-10-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_auto_20201010_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
